server:
  port: 18080

spring:
  profiles: dev

endpoints:
  health:
    sensitive: false
  restart:
    enabled: false
  shutdown:
    enabled: false

management:
  security:
    enabled: false

logging:
  config: 
    classpath:logback-boot.xml
  path: /Users/chenxinjie/logs/oPos/
  level:
    root: INFO